### ISSUE TITLE
Update renderer with factory that creates widgets from questions

### ISSUE THREAD

**Issue by Futsy** [bgrevelt/FakeSwConstructionRepo#16]

**Comment by bgrevelt** [comment]
QLType has been removed.

**Comment by Futsy** [comment]
All enums except for the Operator ones are now gone. The problem remains that we have quite a large amount of options for getting the type in the renderer (would like to discuss).

**Comment by bgrevelt** [comment]
Removed the operator enums (they were not used anymore). So now completely enum free.

**Comment by bgrevelt** [comment]
Use factory to go from question to widget. Factory uses overloads to determine which widget to build.
