### ISSUE TITLE
Use Accept from antlr nodes to make real visitor patterns

### ISSUE THREAD

**Issue by Futsy** [bgrevelt/FakeSwConstructionRepo#24]

**Comment by bgrevelt** [comment]
I think I did this, although I am not 100% sure that this is what Tijs meant. It was a pretty small change.
Let's review this. Commit: 6c904fda2c6f553d167d395392438ab3533efbec

**Comment by Futsy** [comment]
I guess the upside to this longer format is that it is easier recognizable as a visitor?

**Comment by Futsy** [comment]
I still think the new version is shit because we don't use the languages full capability (standard way for a visitor as of 4.0?) but since this looks more like the visitor I guess it works.
