### ISSUE TITLE
Look at different options for Value cleanup

### ISSUE THREAD

**Issue by bgrevelt** [bgrevelt/FakeSwConstructionRepo#35]
Committed two different solutions. One that has the concrete types in the interface (the user will have to cast to dynamic) the other has only the interface types in the interface. In the latter option we cast from IValue to dynamic in the abstract base class

Option 1: df1db4cfc1a760c0300d92599d6d6cc8b244efe7
Option 2: 
097b15fc8d88e41d10e94bda697f528c31553e5a

**Comment by Futsy** [comment]
2nd has pref for me.
