### ISSUE TITLE
Semantic analysis does not fail when keywords are wrong

### ISSUE THREAD

**Issue by bgrevelt** [bgrevelt/FakeSwConstructionRepo#53]
I expected this to be handled by the lexer/parser but it either is not or we don't properly handle parser output. Fact is that when we use bool instead of boolean in the QLS we will get a form with a whole bunch of null nodes and the program will crash.

**Comment by Futsy** [comment]
Antlr has exceptions in node which are exceptions that occured during parsing. Use these to determine if we can go on?
