### ISSUE TITLE
Review unary plus/minus solution

### ISSUE THREAD

**Issue by bgrevelt** [bgrevelt/FakeSwConstructionRepo#9]
We had some problems with unary plus/minus when applied to numbers or decimals. The problem is that we separate -2 into <unary operation minus> and <2>. This gives us problems it the minimum range since abs(int.min) is one higher than int.max. Thus when we pass int.min into a number we will get a semantic error stating that abs(int.max) is out of range for number. I solved this now by taking the unary plus and minus out of the AST:

public INode VisitPositiveOperation(QLNumber number)
        {
            return new QLNumber("+" + number.StringValue);
        }

        public INode VisitPositiveOperation(QLMoney money)
        {
            return new QLMoney("+" + money.StringValue);
        }

        public INode VisitPositiveOperation(IQLExpression expression)
        {
            return new QLPositiveOperation(expression);
        }

        public INode VisitNegativeOperation(QLNumber number)
        {
            return new QLNumber("-" + number.StringValue);            
        }       

        public INode VisitNegativeOperation(QLMoney money)
        {
            return new QLMoney("-" + money.StringValue);
        }

Which seems logical to me becaue I don't really want to have -2 in the AST as an operation, but as a negative number. Still it makes sense to review the idea and especially the code.

**Comment by Futsy** [comment]
The function that calls this throws an InvalidEnumException even though we switch on a string. Changed the exception type and removed some dead code. We could also just use larger numeric types so we don't have to deal with this problem but this makes sense as well. It is a pain from an extensibility viewpoint though (what if we want to add another numerical type?).
